# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-10-01 23:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submitted', models.DateTimeField(auto_now_add=True)),
                ('due_date', models.DateTimeField(auto_now_add=True)),
                ('time_allowance', models.FloatField()),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('waiting', 'Draft'), ('allotted', 'Draft'), ('review', 'Draft'), ('fowarded', 'Draft'), ('complete', 'Draft'), ('revision', 'Draft'), ('dispute', 'Draft')], default='draft', max_length=10)),
                ('fee', models.FloatField()),
                ('accuracy', models.IntegerField()),
                ('rating', models.IntegerField()),
                ('pages', models.IntegerField()),
                ('citations', models.IntegerField()),
                ('provide_references', models.BooleanField()),
                ('discount', models.FloatField()),
                ('words', models.IntegerField()),
                ('title', models.CharField(max_length=100)),
                ('prime', models.BooleanField()),
                ('job_type', models.CharField(choices=[('editing', 'Editing'), ('scratch', 'Scratch')], default='draft', max_length=50)),
                ('deadline', models.CharField(choices=[('3 hours', '3 hours'), ('6 hours', '6 hours'), ('12 hours', '12 hours'), ('24 hours', '24 hours'), ('48 hours', '48 hours'), ('3 days', '3 days'), ('4 days', '4 days'), ('5 days', '5 days'), ('7 days', '7 days'), ('10 days', '10 days'), ('14 days', '14 days'), ('20 days', '20 days'), ('30 days', '30 days')], default='draft', max_length=50)),
                ('formatting', models.CharField(choices=[('APA', 'APA'), ('MLA', 'MLA'), ('Turabian', 'Turabian'), ('Chicago', 'Chicago'), ('Harvard', 'Harvard'), ('Other', 'Other')], default='draft', max_length=50)),
                ('service_type', models.CharField(choices=[('Admission Essay', 'Admission Essay'), ('Annotated Bibliography', 'Annotated Bibliography'), ('Argumentative Essay', 'Argumentative Essay'), ('Book Report', 'Book Report'), ('Assignment', 'Assignment'), ('Movie Review', 'Movie Review'), ('Case Study', 'Case Study'), ('Coursework', 'Coursework'), ('Dissertation', 'Dissertation'), ('Dissertation Chapter - Abstract', 'Dissertation Chapter - Abstract'), ('Dissertation Chapter - Abstract', 'Dissertation Chapter - Abstract'), ('Dissertation Chapter - Abstract', 'Dissertation Chapter - Abstract'), ('Dissertation Chapter - Introduction Chapter', 'Dissertation Chapter - Introduction Chapter'), ('Dissertation Chapter - Literature Review', 'Dissertation Chapter - Literature Review'), ('Dissertation Chapter - Methodology', 'Dissertation Chapter - Methodology'), ('Dissertation Chapter - Results', 'Dissertation Chapter - Results'), ('Dissertation Chapter - Discussion', 'Dissertation Chapter - Discussion'), ('Dissertation Chapter - Hypothesis', 'Dissertation Chapter - Hypothesis'), ('Dissertation Chapter - Conclusion Chapter', 'Dissertation Chapter - Conclusion Chapter'), ('Essay', 'Essay'), ('Formatting', 'Formatting'), ('Lab Report', 'Lab Report'), ('Math Problem', 'Math Problem'), ('Personal Statement', 'Personal Statement'), ('PowerPoint Presentation', 'PowerPoint Presentation'), ('Proofreading', 'Proofreading'), ('Paraphrasing', 'Paraphrasing'), ('Research Paper', 'Research Paper'), ('Research Proposal', 'Research Proposal'), ('Scholarship Essay', 'Scholarship Essay'), ('Speech', 'Speech'), ('Statistics Project', 'Statistics Project'), ('Term Paper', 'Term Paper'), ('Thesis', 'Thesis'), ('Thesis Proposal', 'Thesis Proposal')], default='draft', max_length=50)),
                ('academic_level', models.CharField(choices=[('highschool', 'highschool'), ('college', 'college'), ('university', 'university'), ('masters', 'masters'), ('PhD', 'PhD')], default='draft', max_length=50)),
                ('discpline', models.CharField(choices=[('Arts & Humanities', 'Arts & Humanities'), ('Social Sciences', 'Social Sciences'), ('Sciences', 'Sciences'), ('Information Technology', 'Information Technology'), ('Applied sciences', 'Applied sciences'), ('Economics', 'Economics'), ('Law', 'Law'), ('Other', 'Other')], default='draft', max_length=50)),
                ('spacing', models.CharField(choices=[('double', 'Double'), ('single', 'Single')], default='draft', max_length=50)),
                ('top_assign', models.BooleanField()),
                ('plag_report', models.BooleanField()),
                ('slides', models.IntegerField()),
                ('charts', models.IntegerField()),
                ('paper_detail', models.TextField()),
                ('additional_comment', models.CharField(max_length=10)),
                ('affiliate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Affiliate')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Client')),
            ],
        ),
        migrations.CreateModel(
            name='JobFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upload', models.FileField(upload_to=b'')),
            ],
        ),
        migrations.AddField(
            model_name='job',
            name='job_files',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='job.JobFile'),
        ),
        migrations.AddField(
            model_name='job',
            name='writer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Writer'),
        ),
    ]
